
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 26 20:43:23 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 14;
  public static final int LBRACKET = 41;
  public static final int CHAR = 45;
  public static final int CONST = 3;
  public static final int GRT = 24;
  public static final int GRTEQ = 25;
  public static final int NOTEQUAL = 23;
  public static final int LPAREN = 37;
  public static final int SEMI = 33;
  public static final int CONTINUE = 8;
  public static final int LSEQ = 27;
  public static final int MINUS = 18;
  public static final int RPAREN = 38;
  public static final int AND = 28;
  public static final int LS = 26;
  public static final int OR = 29;
  public static final int BOOL = 44;
  public static final int COMMA = 36;
  public static final int INC = 30;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int ASSIGN = 32;
  public static final int IF = 5;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 22;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int NUMBER = 43;
  public static final int MOD = 21;
  public static final int IDENT = 46;
  public static final int BREAK = 7;
  public static final int VOID = 4;
  public static final int COL = 35;
  public static final int UNION = 16;
  public static final int LBRACE = 39;
  public static final int ELSE = 6;
  public static final int READ = 10;
  public static final int WHILE = 13;
  public static final int RBRACE = 40;
  public static final int PROG = 2;
  public static final int DEC = 31;
  public static final int PRINT = 11;
  public static final int DO = 12;
}

